return {
	eUserLostConn = 0,
	eLoginLogicReq = 1,
	eLoginLogicRes = 2,
	eEnterZoneReq = 3,
	eEnterZoneRes = 4,
	eEnterRoom = 5,
	ePlayerEnterRoom = 6,
	ePlayerExitRoom = 7,
	eExitRoomReq = 8,
	eExitRoomRes = 9,
	eGameStart = 10,
	eUdpTest=11,
	eLogicFrame = 12,
	eNextFrameOpts = 13,
};