//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ServiceProtocol.proto
namespace gprotocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ServiceType")]
    public enum ServiceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_Type", Value=0)]
      INVALID_Type = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Auth", Value=1)]
      Auth = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"System", Value=2)]
      System = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Logic", Value=3)]
      Logic = 3
    }
  
}