//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LogicProtocol.proto
namespace gprotocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicFrame")]
  public partial class LogicFrame : global::ProtoBuf.IExtensible
  {
    public LogicFrame() {}
    
    private int _frameid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int frameid
    {
      get { return _frameid; }
      set { _frameid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpTest")]
  public partial class UdpTest : global::ProtoBuf.IExtensible
  {
    public UdpTest() {}
    
    private int _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginLogicReq")]
  public partial class LoginLogicReq : global::ProtoBuf.IExtensible
  {
    public LoginLogicReq() {}
    
    private string _ip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _udp_port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"udp_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int udp_port
    {
      get { return _udp_port; }
      set { _udp_port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginLogicRes")]
  public partial class LoginLogicRes : global::ProtoBuf.IExtensible
  {
    public LoginLogicRes() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterZoneReq")]
  public partial class EnterZoneReq : global::ProtoBuf.IExtensible
  {
    public EnterZoneReq() {}
    
    private int _zoneid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterZoneRes")]
  public partial class EnterZoneRes : global::ProtoBuf.IExtensible
  {
    public EnterZoneRes() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterRoom")]
  public partial class EnterRoom : global::ProtoBuf.IExtensible
  {
    public EnterRoom() {}
    
    private int _zoneid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private int _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private int _seatid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"seatid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatid
    {
      get { return _seatid; }
      set { _seatid = value; }
    }
    private int _side;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"side", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int side
    {
      get { return _side; }
      set { _side = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEnterRoom")]
  public partial class PlayerEnterRoom : global::ProtoBuf.IExtensible
  {
    public PlayerEnterRoom() {}
    
    private string _unick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string unick
    {
      get { return _unick; }
      set { _unick = value; }
    }
    private int _uface;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uface", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uface
    {
      get { return _uface; }
      set { _uface = value; }
    }
    private int _usex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"usex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int usex
    {
      get { return _usex; }
      set { _usex = value; }
    }
    private int _seatid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"seatid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatid
    {
      get { return _seatid; }
      set { _seatid = value; }
    }
    private int _side;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"side", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int side
    {
      get { return _side; }
      set { _side = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerExitRoom")]
  public partial class PlayerExitRoom : global::ProtoBuf.IExtensible
  {
    public PlayerExitRoom() {}
    
    private int _seatid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seatid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatid
    {
      get { return _seatid; }
      set { _seatid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterRoomRes")]
  public partial class EnterRoomRes : global::ProtoBuf.IExtensible
  {
    public EnterRoomRes() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitRoomRes")]
  public partial class ExitRoomRes : global::ProtoBuf.IExtensible
  {
    public ExitRoomRes() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStart")]
  public partial class GameStart : global::ProtoBuf.IExtensible
  {
    public GameStart() {}
    
    private readonly global::System.Collections.Generic.List<int> _heros = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"heros", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> heros
    {
      get { return _heros; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"LogicCmd")]
    public enum LogicCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Invalid_Logic_Cmd", Value=0)]
      Invalid_Logic_Cmd = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eLoginLogicReq", Value=1)]
      eLoginLogicReq = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eLoginLogicRes", Value=2)]
      eLoginLogicRes = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eEnterZoneReq", Value=3)]
      eEnterZoneReq = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eEnterZoneRes", Value=4)]
      eEnterZoneRes = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eEnterRoom", Value=5)]
      eEnterRoom = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ePlayerEnterRoom", Value=6)]
      ePlayerEnterRoom = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ePlayerExitRoom", Value=7)]
      ePlayerExitRoom = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eExitRoomReq", Value=8)]
      eExitRoomReq = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eExitRoomRes", Value=9)]
      eExitRoomRes = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eGameStart", Value=10)]
      eGameStart = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eUdpTest", Value=11)]
      eUdpTest = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eLogicFrame", Value=12)]
      eLogicFrame = 12
    }
  
}