//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MobaProtocol.proto
namespace gprotocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecvLoginBonuesRes")]
  public partial class RecvLoginBonuesRes : global::ProtoBuf.IExtensible
  {
    public RecvLoginBonuesRes() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserGameInfo")]
  public partial class UserGameInfo : global::ProtoBuf.IExtensible
  {
    public UserGameInfo() {}
    
    private int _ucoin_1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ucoin_1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ucoin_1
    {
      get { return _ucoin_1; }
      set { _ucoin_1 = value; }
    }
    private int _ucoin_2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ucoin_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ucoin_2
    {
      get { return _ucoin_2; }
      set { _ucoin_2 = value; }
    }
    private int _uexp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"uexp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uexp
    {
      get { return _uexp; }
      set { _uexp = value; }
    }
    private int _uvip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"uvip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uvip
    {
      get { return _uvip; }
      set { _uvip = value; }
    }
    private int _uitem_1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"uitem_1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uitem_1
    {
      get { return _uitem_1; }
      set { _uitem_1 = value; }
    }
    private int _uitem_2;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"uitem_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uitem_2
    {
      get { return _uitem_2; }
      set { _uitem_2 = value; }
    }
    private int _bonues_status;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"bonues_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bonues_status
    {
      get { return _bonues_status; }
      set { _bonues_status = value; }
    }
    private int _bonues;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"bonues", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bonues
    {
      get { return _bonues; }
      set { _bonues = value; }
    }
    private int _days;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"days", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int days
    {
      get { return _days; }
      set { _days = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMobaInfoRes")]
  public partial class GetMobaInfoRes : global::ProtoBuf.IExtensible
  {
    public GetMobaInfoRes() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private UserGameInfo _uinfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UserGameInfo uinfo
    {
      get { return _uinfo; }
      set { _uinfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MobaCmd")]
    public enum MobaCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_LOGIN_CMD", Value=0)]
      INVALID_LOGIN_CMD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eGetMobaInfoReq", Value=1)]
      eGetMobaInfoReq = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eGetMobaInfoRes", Value=2)]
      eGetMobaInfoRes = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eRecvLoginBonuesReq", Value=3)]
      eRecvLoginBonuesReq = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eRecvLoginBonuesRes", Value=4)]
      eRecvLoginBonuesRes = 4
    }
  
}