//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/LogicProtocol.proto
namespace PurificationPioneer.Network.ProtoGen
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginLogicReq")]
  public partial class LoginLogicReq : global::ProtoBuf.IExtensible
  {
    public LoginLogicReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginLogicRes")]
  public partial class LoginLogicRes : global::ProtoBuf.IExtensible
  {
    public LoginLogicRes() {}
    
    private string _udp_ip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"udp_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string udp_ip
    {
      get { return _udp_ip; }
      set { _udp_ip = value; }
    }
    private int _udp_port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"udp_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int udp_port
    {
      get { return _udp_port; }
      set { _udp_port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpTestReq")]
  public partial class UdpTestReq : global::ProtoBuf.IExtensible
  {
    public UdpTestReq() {}
    
    private string _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpTestRes")]
  public partial class UdpTestRes : global::ProtoBuf.IExtensible
  {
    public UdpTestRes() {}
    
    private string _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartMatchReq")]
  public partial class StartMatchReq : global::ProtoBuf.IExtensible
  {
    public StartMatchReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartMatchRes")]
  public partial class StartMatchRes : global::ProtoBuf.IExtensible
  {
    public StartMatchRes() {}
    
    private int _current;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"current", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int current
    {
      get { return _current; }
      set { _current = value; }
    }
    private int _max;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max
    {
      get { return _max; }
      set { _max = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopMatchReq")]
  public partial class StopMatchReq : global::ProtoBuf.IExtensible
  {
    public StopMatchReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopMatchRes")]
  public partial class StopMatchRes : global::ProtoBuf.IExtensible
  {
    public StopMatchRes() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchInfo")]
  public partial class MatchInfo : global::ProtoBuf.IExtensible
  {
    public MatchInfo() {}
    
    private string _unick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string unick
    {
      get { return _unick; }
      set { _unick = value; }
    }
    private int _urank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"urank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int urank
    {
      get { return _urank; }
      set { _urank = value; }
    }
    private int _seatId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"seatId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatId
    {
      get { return _seatId; }
      set { _seatId = value; }
    }
    private int _uface;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"uface", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uface
    {
      get { return _uface; }
      set { _uface = value; }
    }
    private int _ulevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ulevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ulevel
    {
      get { return _ulevel; }
      set { _ulevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FinishMatchTick")]
  public partial class FinishMatchTick : global::ProtoBuf.IExtensible
  {
    public FinishMatchTick() {}
    
    private readonly global::System.Collections.Generic.List<MatchInfo> _matchers = new global::System.Collections.Generic.List<MatchInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"matchers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MatchInfo> matchers
    {
      get { return _matchers; }
    }
  
    private int _heroSelectTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"heroSelectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroSelectTime
    {
      get { return _heroSelectTime; }
      set { _heroSelectTime = value; }
    }
    private int _roomId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectHeroReq")]
  public partial class SelectHeroReq : global::ProtoBuf.IExtensible
  {
    public SelectHeroReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private int _hero_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectHeroRes")]
  public partial class SelectHeroRes : global::ProtoBuf.IExtensible
  {
    public SelectHeroRes() {}
    
    private int _seatId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seatId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatId
    {
      get { return _seatId; }
      set { _seatId = value; }
    }
    private int _hero_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitHeroReq")]
  public partial class SubmitHeroReq : global::ProtoBuf.IExtensible
  {
    public SubmitHeroReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitHeroRes")]
  public partial class SubmitHeroRes : global::ProtoBuf.IExtensible
  {
    public SubmitHeroRes() {}
    
    private int _seatId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seatId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatId
    {
      get { return _seatId; }
      set { _seatId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateSelectTimer")]
  public partial class UpdateSelectTimer : global::ProtoBuf.IExtensible
  {
    public UpdateSelectTimer() {}
    
    private int _current;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"current", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int current
    {
      get { return _current; }
      set { _current = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ForceSelect")]
  public partial class ForceSelect : global::ProtoBuf.IExtensible
  {
    public ForceSelect() {}
    
    private readonly global::System.Collections.Generic.List<SelectHeroRes> _selectResults = new global::System.Collections.Generic.List<SelectHeroRes>();
    [global::ProtoBuf.ProtoMember(1, Name=@"selectResults", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SelectHeroRes> selectResults
    {
      get { return _selectResults; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInput")]
  public partial class PlayerInput : global::ProtoBuf.IExtensible
  {
    public PlayerInput() {}
    
    private int _seatId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seatId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatId
    {
      get { return _seatId; }
      set { _seatId = value; }
    }
    private int _moveX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"moveX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveX
    {
      get { return _moveX; }
      set { _moveX = value; }
    }
    private int _moveY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"moveY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveY
    {
      get { return _moveY; }
      set { _moveY = value; }
    }
    private bool _jump;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"jump", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool jump
    {
      get { return _jump; }
      set { _jump = value; }
    }
    private int _mouseX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mouseX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mouseX
    {
      get { return _mouseX; }
      set { _mouseX = value; }
    }
    private int _mouseY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"mouseY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mouseY
    {
      get { return _mouseY; }
      set { _mouseY = value; }
    }
    private bool _attack;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private bool _heroFirstSkill;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"heroFirstSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool heroFirstSkill
    {
      get { return _heroFirstSkill; }
      set { _heroFirstSkill = value; }
    }
    private bool _heroSecondSkill;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"heroSecondSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool heroSecondSkill
    {
      get { return _heroSecondSkill; }
      set { _heroSecondSkill = value; }
    }
    private bool _weaponFirstSkill;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"weaponFirstSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool weaponFirstSkill
    {
      get { return _weaponFirstSkill; }
      set { _weaponFirstSkill = value; }
    }
    private bool _weaponSecondSkill;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"weaponSecondSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool weaponSecondSkill
    {
      get { return _weaponSecondSkill; }
      set { _weaponSecondSkill = value; }
    }
    private int _faceX;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"faceX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int faceX
    {
      get { return _faceX; }
      set { _faceX = value; }
    }
    private int _faceY;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"faceY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int faceY
    {
      get { return _faceY; }
      set { _faceY = value; }
    }
    private int _faceZ;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"faceZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int faceZ
    {
      get { return _faceZ; }
      set { _faceZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicFrame")]
  public partial class LogicFrame : global::ProtoBuf.IExtensible
  {
    public LogicFrame() {}
    
    private int _frameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int frameId
    {
      get { return _frameId; }
      set { _frameId = value; }
    }
    private readonly global::System.Collections.Generic.List<PlayerInput> _inputs = new global::System.Collections.Generic.List<PlayerInput>();
    [global::ProtoBuf.ProtoMember(2, Name=@"inputs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerInput> inputs
    {
      get { return _inputs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NextFrameInput")]
  public partial class NextFrameInput : global::ProtoBuf.IExtensible
  {
    public NextFrameInput() {}
    
    private int _frameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int frameId
    {
      get { return _frameId; }
      set { _frameId = value; }
    }
    private int _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _roomType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _seatId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"seatId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatId
    {
      get { return _seatId; }
      set { _seatId = value; }
    }
    private readonly global::System.Collections.Generic.List<PlayerInput> _inputs = new global::System.Collections.Generic.List<PlayerInput>();
    [global::ProtoBuf.ProtoMember(5, Name=@"inputs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerInput> inputs
    {
      get { return _inputs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicFramesToSync")]
  public partial class LogicFramesToSync : global::ProtoBuf.IExtensible
  {
    public LogicFramesToSync() {}
    
    private int _frameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int frameId
    {
      get { return _frameId; }
      set { _frameId = value; }
    }
    private readonly global::System.Collections.Generic.List<LogicFrame> _unsyncFrames = new global::System.Collections.Generic.List<LogicFrame>();
    [global::ProtoBuf.ProtoMember(2, Name=@"unsyncFrames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LogicFrame> unsyncFrames
    {
      get { return _unsyncFrames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartGameReq")]
  public partial class StartGameReq : global::ProtoBuf.IExtensible
  {
    public StartGameReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartGameRes")]
  public partial class StartGameRes : global::ProtoBuf.IExtensible
  {
    public StartGameRes() {}
    
    private int _gameTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameTime
    {
      get { return _gameTime; }
      set { _gameTime = value; }
    }
    private int _randSeed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"randSeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int randSeed
    {
      get { return _randSeed; }
      set { _randSeed = value; }
    }
    private int _logicFrameDeltaTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"logicFrameDeltaTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int logicFrameDeltaTime
    {
      get { return _logicFrameDeltaTime; }
      set { _logicFrameDeltaTime = value; }
    }
    private int _startGameDelay;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"startGameDelay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startGameDelay
    {
      get { return _startGameDelay; }
      set { _startGameDelay = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitUdpReq")]
  public partial class InitUdpReq : global::ProtoBuf.IExtensible
  {
    public InitUdpReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}