//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/LogicProtocol.proto
namespace PurificationPioneer.Network.ProtoGen
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginLogicRes")]
  public partial class LoginLogicRes : global::ProtoBuf.IExtensible
  {
    public LoginLogicRes() {}
    
    private string _udp_ip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"udp_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string udp_ip
    {
      get { return _udp_ip; }
      set { _udp_ip = value; }
    }
    private int _udp_port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"udp_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int udp_port
    {
      get { return _udp_port; }
      set { _udp_port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpTestReq")]
  public partial class UdpTestReq : global::ProtoBuf.IExtensible
  {
    public UdpTestReq() {}
    
    private string _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpTestRes")]
  public partial class UdpTestRes : global::ProtoBuf.IExtensible
  {
    public UdpTestRes() {}
    
    private string _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartMatchReq")]
  public partial class StartMatchReq : global::ProtoBuf.IExtensible
  {
    public StartMatchReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartMatchRes")]
  public partial class StartMatchRes : global::ProtoBuf.IExtensible
  {
    public StartMatchRes() {}
    
    private int _current;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"current", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int current
    {
      get { return _current; }
      set { _current = value; }
    }
    private int _max;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max
    {
      get { return _max; }
      set { _max = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopMatchReq")]
  public partial class StopMatchReq : global::ProtoBuf.IExtensible
  {
    public StopMatchReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopMatchRes")]
  public partial class StopMatchRes : global::ProtoBuf.IExtensible
  {
    public StopMatchRes() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchInfo")]
  public partial class MatchInfo : global::ProtoBuf.IExtensible
  {
    public MatchInfo() {}
    
    private string _unick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string unick
    {
      get { return _unick; }
      set { _unick = value; }
    }
    private int _urank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"urank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int urank
    {
      get { return _urank; }
      set { _urank = value; }
    }
    private int _seatId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"seatId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatId
    {
      get { return _seatId; }
      set { _seatId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FinishMatchTick")]
  public partial class FinishMatchTick : global::ProtoBuf.IExtensible
  {
    public FinishMatchTick() {}
    
    private readonly global::System.Collections.Generic.List<MatchInfo> _matchers = new global::System.Collections.Generic.List<MatchInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"matchers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MatchInfo> matchers
    {
      get { return _matchers; }
    }
  
    private int _heroSelectTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"heroSelectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroSelectTime
    {
      get { return _heroSelectTime; }
      set { _heroSelectTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectHeroReq")]
  public partial class SelectHeroReq : global::ProtoBuf.IExtensible
  {
    public SelectHeroReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private int _hero_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectHeroRes")]
  public partial class SelectHeroRes : global::ProtoBuf.IExtensible
  {
    public SelectHeroRes() {}
    
    private int _seatId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seatId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatId
    {
      get { return _seatId; }
      set { _seatId = value; }
    }
    private int _hero_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitHeroReq")]
  public partial class SubmitHeroReq : global::ProtoBuf.IExtensible
  {
    public SubmitHeroReq() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitHeroRes")]
  public partial class SubmitHeroRes : global::ProtoBuf.IExtensible
  {
    public SubmitHeroRes() {}
    
    private int _seatId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seatId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatId
    {
      get { return _seatId; }
      set { _seatId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateSelectTimer")]
  public partial class UpdateSelectTimer : global::ProtoBuf.IExtensible
  {
    public UpdateSelectTimer() {}
    
    private int _current;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"current", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int current
    {
      get { return _current; }
      set { _current = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ForceSelect")]
  public partial class ForceSelect : global::ProtoBuf.IExtensible
  {
    public ForceSelect() {}
    
    private readonly global::System.Collections.Generic.List<SelectHeroRes> _selectResults = new global::System.Collections.Generic.List<SelectHeroRes>();
    [global::ProtoBuf.ProtoMember(1, Name=@"selectResults", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SelectHeroRes> selectResults
    {
      get { return _selectResults; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}